In [1]:
import numpy as np

#### Problem Statement 1:
#### Write a function so that the columns of the output matrix are powers of the input vector.

#### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

#### HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [2]:
def vandermonde_matrix(input_matrix, N, order):
    output_matrix = np.array(list(np.array(input_matrix, ndmin=2)) * N).T
    dim = np.ndim(output_matrix)
    if(order):
        print("Output Matrix if the Order of the power is increasing is :", sep='/n')
        pow_second_para = np.arange(0, N, 1)
        # pow_second_para = np.linspace(0, N-1, N, dtype=int)
    else:
        print("Output Matrix if the Order of the power is decreasing is :", sep='/n')
        pow_second_para = np.arange(N-1, -1, -1)
        # pow_second_para = np.linspace(N-1, 0, N, dtype=int)

    output_matrix = np.power(output_matrix, pow_second_para)
    print(output_matrix)

In [3]:
input_matrix = np.array([1, 2, 3, 4, 5])
no_of_col = 3                        # number of columns

print("Input Matrix :", input_matrix)
print("Number of columns in the output Matrix :", no_of_col)
print("-"*70)

increasing_order = True  
vandermonde_matrix(input_matrix, no_of_col, increasing_order)

print("-"*70)
      
increasing_order = False
vandermonde_matrix(input_matrix, no_of_col, increasing_order)

Input Matrix : [1 2 3 4 5]
Number of columns in the output Matrix : 3
----------------------------------------------------------------------
Output Matrix if the Order of the power is increasing is :
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]
----------------------------------------------------------------------
Output Matrix if the Order of the power is decreasing is :
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


#### Problem Statement 2:
#### Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
#### The moving average sequence has n-k+1 elements as shown below.
#### The moving averages with k=4 of a ten-value sequence (n=10) is shown below
####  i    1  2  3  4  5  6  7  8  9  10
#### ===== == == == == == == == == == ==
#### Input 10 20 30 40 50 60 70 80 90 100
#### y1    25 = (10+20+30+40)/4
#### y2    35 = (20+30+40+50)/4
#### y3    45 = (30+40+50+60)/4
#### y4    55 = (40+50+60+70)/4
#### y5    65 = (50+60+70+80)/4
#### y6    75 = (60+70+80+90)/4
#### y7    85 = (70+80+90+100)/4
#### Thus, the moving average sequence has n-k+1=10-4+1=7 values.

#### Question: Write a function to find moving average in an array over a window:
#### Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
def traditional_approach(input, k):
    output = []
    moving_avg_seq = input.size - k + 1       # moving average sequence size (output y)
    for i in np.arange(moving_avg_seq):
        y = 0
        for j in np.arange(k):
            y = y + input[i+j]
        y = y/k
        output.append(y)
    return output

In [5]:
def moving_average(input, k):
    moving_avg_seq = input.size - k + 1
    output = np.cumsum(input)
    #output[k:] = output[k:] - output[:(moving_avg_seq - 1)]
    output[k:] = output[k:] - output[:(input.size - k)]
    output = output[k-1:] / k
    return output

In [13]:
seq_size = 10                             # sequence size (input x)
window = 3                                # window

#input = np.arange(1, seq_size+1)*10
input = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

print("Input Matrix :", input)
print("Size of the given a sequence (n):", input.size)
print("Window size (k) :", window)
print("moving average sequence has n-k+1 :", input.size-window+1)

print("-"*100)
print("Moving average in an array (traditional approach) :", traditional_approach(input, window))

print("-"*100)
print("Moving average in an array :", moving_average(input, window))

Input Matrix : [  3   5   7   2   8  10  11  65  72  81  99 100 150]
Size of the given a sequence (n): 13
Window size (k) : 3
moving average sequence has n-k+1 : 11
----------------------------------------------------------------------------------------------------
Moving average in an array (traditional approach) : [5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
----------------------------------------------------------------------------------------------------
Moving average in an array : [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
